### ISSUE TITLE
Help RetinoProc stimulus 

### ISSUE THREAD

**Issue by LucaC1997** [afni/afni_boutiques#1]
Hello Afni experts
I am trying to use RetinoProc for a retinotopy analysis and I have a doubt about it. In the various scripts in the demo I see that there is no input field in which to enter the initial phase of my visual stimulus (be it the wedge for polar angles or the ring for eccentricity). Should I assume that whatever the initial phase of the stimulus is, the result is not affected, or does Afni take a default value (such as zero degrees for the wedge) as the initial phase?
Thanks in advance for your answer!!!

Luca

**Comment by mrneont** [comment]
Closing this issue here because the same thing has been asked simultaneously here: https://github.com/afni/afni/issues/444, and the latter is the more appropriate spot for code questions.
